import { Session } from "./Interface/session";

export const sessions: Session[] = [
	{
		id: 1,
		title: "Sunday Football",
		about: "Friendly 7v7 football session. All skill levels are welcome. Bring your boots and water bottle.",
		sport: "Football",
		sportEmoji: "⚽",
		date: "16 Feb • 7:00 AM",
		location: "Siri Fort Sports Complex",
		distance: "2.4 km",
		price: "Free",
		status: "OPEN",
		joined: true,
		currentPlayers: 7,
		maxPlayers: 10,
		openSpots: 3,
	},
	{
		id: 2,
		title: "Morning Badminton",
		about: "Doubles badminton games for intermediate players. Racquets available if needed.",
		sport: "Badminton",
		sportEmoji: "🏸",
		date: "15 Feb • 8:30 AM",
		location: "Delhi Sports Club",
		distance: "3.8 km",
		price: "₹150",
		status: "OPEN",
		joined: false,
		currentPlayers: 4,
		maxPlayers: 8,
		openSpots: 4,
	},
	{
		id: 3,
		title: "Weekend Cricket",
		about: "25-over friendly cricket match. Looking for batsmen and fast bowlers.",
		sport: "Cricket",
		sportEmoji: "🏏",
		date: "6 Feb • 6:30 AM",
		location: "Dwarka Sports Complex",
		distance: "5.2 km",
		price: "₹100",
		status: "FULL",
		joined: false,
		currentPlayers: 22,
		maxPlayers: 22,
		openSpots: 0,
	},
];
